function love.conf(t)
    t.accelerometerjoystick = false -- Enable the accelerometer on iOS and Android by exposing it as a Joystick (boolean)
    t.externalstorage = true -- True to save files (and read from the save directory) in external storage on Android (boolean) 
    t.audio.mic = false -- Request and use microphone capabilities in Android (boolean)
    t.audio.mixwithsystem = true -- Keep background music playing when opening LOVE (boolean, iOS and Android only)
    t.window.icon = nil -- Filepath to an image to use as the window's icon (string)
    t.window.borderless = false -- Remove all border visuals from the window (boolean)
    t.modules.audio = false -- Enable the audio module (boolean)
    t.modules.data = true -- Enable the data module (boolean)
    t.modules.event = true -- Enable the event module (boolean)
    t.modules.font = true -- Enable the font module (boolean)
    t.modules.graphics = true -- Enable the graphics module (boolean)
    t.modules.image = false -- Enable the image module (boolean)
    t.modules.joystick = false -- Enable the joystick module (boolean)
    t.modules.keyboard = false -- Enable the keyboard module (boolean)
    t.modules.math = true -- Enable the math module (boolean)
    t.modules.mouse = true -- Enable the mouse module (boolean)
    t.modules.physics = false -- Enable the physics module (boolean)
    t.modules.sound = false -- Enable the sound module (boolean)
    t.modules.system = true -- Enable the system module (boolean)
    t.modules.thread = true -- Enable the thread module (boolean)
    t.modules.timer = true -- Enable the timer module (boolean), Disabling it will result 0 delta time in love.update
    t.modules.touch = false -- Enable the touch module (boolean)
    t.modules.video = false -- Enable the video module (boolean)
    t.modules.window = true -- Enable the window module (boolean)
end
